# Generated by Django 4.2 on 2025-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mainPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phrase', models.TextField()),
                ('updated_phrase', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='poolPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharse', models.TextField()),
            ],
        ),
    ]
