# Generated by Django 4.2 on 2025-01-23 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='mainTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.TextField()),
                ('check_time', models.DateField()),
                ('deadline_time', models.DateField()),
                ('count_time_to_deadline', models.IntegerField()),
                ('feature_task', models.IntegerField()),
                ('title', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('who_get_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_tasks', to=settings.AUTH_USER_MODEL)),
                ('who_set_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
