# Generated by Django 4.2 on 2025-01-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userlogin', models.CharField(max_length=100, unique=True)),
                ('f', models.TextField(max_length=100)),
                ('i', models.TextField(max_length=100)),
                ('o', models.TextField(max_length=100)),
                ('rank', models.TextField(max_length=100)),
                ('doljnost', models.TextField(max_length=100)),
                ('data_registration', models.DateField(auto_now_add=True)),
                ('role_task', models.IntegerField(default=55)),
                ('is_active', models.BooleanField(default=True)),
                ('is_super', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('bossCM', 'BossCM'), ('simple-cm', 'SimpleCM'), ('other-user', 'OtherUsers')], default='other-user', max_length=25)),
                ('groups', models.ManyToManyField(blank=True, related_name='customer_group', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customer_premissions', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
